version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rabbit:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_VHOST: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  mysql_data: